### ISSUE TITLE
Node problem

### ISSUE THREAD

**Issue by wahshibinharb** [airsend-io/nodeutil#1]
when i try to install i am getting error some of nodes  not running 

![e285bc99-7bbe-4dfd-8182-4bc5eaa4127e](https://user-images.githubusercontent.com/49900792/210942295-a57f2139-277f-4fac-9f56-ebcde7bf0f01.jpg)
![7126e537-68a1-4483-99a0-03e994419cba](https://user-images.githubusercontent.com/49900792/210942308-67ed0a43-c528-41e3-aa5b-b4ba210412ce.jpg)
![8b971cef-4a6d-47ba-abb3-d1f8f3db8e64](https://user-images.githubusercontent.com/49900792/210942322-2b2e0d87-fa93-4e92-a5ba-5702ecac7b40.jpg)

any help ?

**Comment by jefersonralmeida** [comment]
Hi Vincent. Thanks for reporting.

Could you let me know in which OS you're trying to build the environment?

Looks like you're using our dockerized environment, right?

**Comment by wahshibinharb** [comment]
Hello Jeferson

Ubuntu 20.04 LTS
Docker Compose version v2.14.2

**Comment by jefersonralmeida** [comment]
We reproduced the problem here, we'll be checking, and let you know.

**Comment by jefersonralmeida** [comment]
Hey @vincentpricex, this [commit](https://github.com/airsend-io/devenv/commit/61275fa1b11b0b2d3887172595c092f9a5a186f1) should fix the issue (fixed for me).

I recommend you delete these folders if they were created on your env:
- api
- nodeutils
- kafka
- webrtc
- websocket
- ui

After removing them (those folders are git-ignored on the `devenv` repository), please try to run the build script again.

Please let us know if you see any additional problems (the environment setup is a new piece developed exclusively for the open-sourcing project, so it may be susceptible to problems).

**Comment by vincentpricex** [comment]
![7f6b7dab-c589-4aca-9a1d-7907cb0bb56c](https://user-images.githubusercontent.com/49900792/211545457-91904fb8-88fc-405e-934b-90cc7666785c.jpg)
Error response from daemon: Conflict. The container name "/airsend.kafka.worker.high" is already in use by container "bc8d2d3c78bc9597afc595dd059ea640b8b562e37652c584e4c39d66dfcfec08". You have to remove (or rename) that container to be able to reuse that name.
